CREATE ALGORITHM=UNDEFINED DEFINER=`fav`@`%` SQL SECURITY DEFINER VIEW `v_func` AS select sql_no_cache `func`.`id` AS `id`,`func`.`name` AS `name`,`func`.`url` AS `url`,`func`.`front_func` AS `front_func`,`func`.`user_type` AS `user_type`,`func`.`binding` AS `binding`,`rf`.`role_id` AS `role_id`,`ur`.`user_id` AS `user_id` from ((`ts_func` `func` left join `tb_role_func` `rf` on((`func`.`id` = `rf`.`func_id`))) left join `tb_user_role` `ur` on((`rf`.`role_id` = `ur`.`role_id`))) where (`func`.`use_flag` = 1) order by `ur`.`user_id`;
CREATE ALGORITHM=UNDEFINED DEFINER=`fav`@`%` SQL SECURITY DEFINER VIEW `v_navigation` AS select sql_no_cache `nav`.`id` AS `id`,`nav`.`name` AS `name`,`nav`.`target` AS `target`,`func`.`url` AS `url`,`nav`.`upper_id` AS `upper_id`,`func`.`user_type` AS `user_type`,`nav`.`view_order` AS `view_order`,`rf`.`role_id` AS `role_id`,`ur`.`user_id` AS `user_id` from (`ts_func` `func` join ((`ts_navigation` `nav` left join `tb_role_func` `rf` on((`nav`.`func_id` = `rf`.`func_id`))) left join `tb_user_role` `ur` on((`rf`.`role_id` = `ur`.`role_id`)))) where ((`nav`.`func_id` = `func`.`id`) and (`nav`.`use_flag` = 1) and (`func`.`use_flag` = 1)) order by `ur`.`user_id`,`nav`.`target`,`nav`.`view_order`;

INSERT INTO `tb_user` VALUES (1, 'admin', 'c66579cc40752d7879ec2c2ac1a38c3c', '111111', 'admin', NULL, '12@126.com', '2s', NULL, NULL, NULL, NULL, '4', NULL, NULL, NULL, '/upload/file/2014-07/20140717095700003444.jpg', NULL, '1', '1', NULL, '0', 1, '2015-6-11 03:10:05', 0, '2015-9-7 10:39:12', 1, '/upload/file/20150815122811.png', '2222', '1111', '22222', 256, NULL);

INSERT INTO `tb_user_role` VALUES (62, 1, 1, 0, 1, '2014-7-15 08:25:47', 1, '0000-0-0 00:00:00', NULL);

INSERT INTO `ts_func` VALUES (1, '基础信息', '1', '/module/module_center.do', NULL, '1', 1, '2010-6-11 03:10:12', 0, '0000-0-0 00:00:00', NULL);
INSERT INTO `ts_func` VALUES (2, '系统设置', '1', '/module/module_center.do', NULL, '1', 1, '2010-6-11 03:10:12', 0, '0000-0-0 00:00:00', NULL);
INSERT INTO `ts_func` VALUES (70000, '系统管理', '2', '/module/module_center.do', NULL, '1', 1, '2010-6-11 03:10:11', 0, '0000-0-0 00:00:00', NULL);
INSERT INTO `ts_func` VALUES (70100, '用户管理', '2', '/module/system/user_init.do', 70000, '1', 0, '2010-6-11 03:10:11', 0, '0000-0-0 00:00:00', NULL);
INSERT INTO `ts_func` VALUES (70101, '用户管理', '2', '/module/system/user_init.do', 70000, '2', 1, '2010-6-11 03:10:11', 0, '0000-0-0 00:00:00', NULL);
INSERT INTO `ts_func` VALUES (70102, '用户查询', '2', '/module/system/user_query.do', 70101, '3', 1, '2010-6-11 03:10:11', 0, '0000-0-0 00:00:00', NULL);
INSERT INTO `ts_func` VALUES (70103, '用户添加', '2', '/module/system/user_add.do', 70101, '2', 1, '2010-6-11 03:10:11', 0, '0000-0-0 00:00:00', NULL);
INSERT INTO `ts_func` VALUES (70104, '用户保存', '2', '/module/system/user_save.do', 70101, '3', 1, '2010-6-11 03:10:11', 0, '0000-0-0 00:00:00', NULL);
INSERT INTO `ts_func` VALUES (70105, '用户编辑', '2', '/module/system/user_edit.do', 70101, '2', 1, '2010-6-11 03:10:11', 0, '0000-0-0 00:00:00', NULL);
INSERT INTO `ts_func` VALUES (70106, '用户修改', '2', '/module/system/user_update.do', 70101, '3', 1, '2010-6-11 03:10:11', 0, '0000-0-0 00:00:00', NULL);
INSERT INTO `ts_func` VALUES (70107, '用户查看', '2', '/module/system/user_view.do', 70101, '1', 1, '2010-6-11 03:10:11', 0, '0000-0-0 00:00:00', NULL);
INSERT INTO `ts_func` VALUES (70108, '用户删除', '2', '/module/system/user_delete.do', 70101, '1', 1, '2010-6-11 03:10:11', 0, '0000-0-0 00:00:00', NULL);
INSERT INTO `ts_func` VALUES (70500, '登录日志查询', '2', '/module/admin/loginLog_init.do', 70000, '2', 1, '2010-6-11 03:10:12', 0, '0000-0-0 00:00:00', 0);
INSERT INTO `ts_func` VALUES (70501, '登录日志查询', '2', '/module/admin/loginLog_query.do', 70500, '3', 1, '2010-6-11 03:10:12', 0, '0000-0-0 00:00:00', 0);
INSERT INTO `ts_func` VALUES (70502, '登录日志删除', '2', '/module/admin/loginLog_deletes.do', 70500, '3', 1, '2010-6-11 03:10:12', 0, '0000-0-0 00:00:00', 0);
INSERT INTO `ts_func` VALUES (70600, '角色管理', '2', '/module/system/role_init.do', 70000, '2', 1, '2010-6-11 03:10:12', 0, '0000-0-0 00:00:00', NULL);
INSERT INTO `ts_func` VALUES (70601, '角色查询', '2', '/module/system/role_query.do', 70600, '3', 1, '2010-6-11 03:10:12', 0, '0000-0-0 00:00:00', NULL);
INSERT INTO `ts_func` VALUES (70602, '角色查看', '2', '/module/system/role_view.do', 70600, '1', 1, '2010-6-11 03:10:12', 0, '0000-0-0 00:00:00', NULL);
INSERT INTO `ts_func` VALUES (70603, '角色添加', '2', '/module/system/role_add.do', 70600, '2', 1, '2010-6-11 03:10:12', 0, '0000-0-0 00:00:00', NULL);
INSERT INTO `ts_func` VALUES (70604, '角色保存', '2', '/module/system/role_save.do', 70603, '3', 1, '2010-6-11 03:10:12', 0, '0000-0-0 00:00:00', NULL);
INSERT INTO `ts_func` VALUES (70605, '角色编辑', '2', '/module/system/role_edit.do', 70600, '2', 1, '2010-6-11 03:10:12', 0, '0000-0-0 00:00:00', NULL);
INSERT INTO `ts_func` VALUES (70606, '角色修改', '2', '/module/system/role_update.do', 70605, '3', 1, '2010-6-11 03:10:12', 0, '0000-0-0 00:00:00', NULL);
INSERT INTO `ts_func` VALUES (70607, '角色删除', '2', '/module/system/role_delete.do', 70600, '1', 1, '2010-6-11 03:10:12', 0, '0000-0-0 00:00:00', NULL);
INSERT INTO `ts_func` VALUES (70608, '角色功能树', '2', '/module/system/role_toTree.do', 70600, '3', 1, '2010-6-11 03:10:12', 0, '0000-0-0 00:00:00', NULL);
INSERT INTO `ts_func` VALUES (70609, '功能树节点', '2', '/module/system/role_treeNodes.do', 70600, '3', 1, '2010-6-11 03:10:12', 0, '0000-0-0 00:00:00', NULL);


INSERT INTO `ts_navigation` VALUES (70101, 70101, '用户管理', 1, NULL, '系统管理', 1, '2010-6-11 03:10:12', 0, '0000-0-0 00:00:00', NULL);
INSERT INTO `ts_navigation` VALUES (70500, 70500, '登录日志', 2, NULL, '系统管理', 1, '2010-6-11 03:10:12', 0, '0000-0-0 00:00:00', 0);
INSERT INTO `ts_navigation` VALUES (70600, 70600, '角色管理', 3, NULL, '系统管理', 1, '2010-6-11 03:10:12', 0, '0000-0-0 00:00:00', NULL);


INSERT INTO `tb_role` VALUES (1, '系统管理员', '0', 0, 1, '2010-6-11 03:10:05', 1, '2011-5-30 10:44:12', 1);

INSERT INTO `tb_role_func` VALUES (1, 1, 1, 1, '2011-5-30 10:44:13', 1, '0000-0-0 00:00:00', NULL);
INSERT INTO `tb_role_func` VALUES (2, 2, 1, 1, '2011-5-30 10:44:13', 1, '0000-0-0 00:00:00', NULL);
INSERT INTO `tb_role_func` VALUES (1000, 70101, 1, 1, '2011-5-30 10:44:13', 1, '0000-0-0 00:00:00', NULL);
INSERT INTO `tb_role_func` VALUES (1001, 70600, 1, 1, '2011-5-30 10:44:13', 1, '0000-0-0 00:00:00', NULL);
INSERT INTO `tb_role_func` VALUES (1002, 70500, 1, 1, '2011-5-30 10:44:13', 1, '0000-0-0 00:00:00', NULL);


INSERT INTO `ts_codebook` VALUES ('common-share_flag', '0', '私有', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('common-use_flag', '0', '删除', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('event-effect', '0', '无影响', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('node-type', '0', 'none', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('product_is_new', '0', '否', 3, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('task-level', '0', '紧急', 1, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('tb_alarm-confirm_status', '0', '未确认', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('tb_user-staff_type', '0', '手机端', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('user_vip_flag', '0', '否', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('common-rp_type', '01', '行政奖励', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('criminal_month_assess', '01', '遵纪守法认罪服罚情况(综合表现)', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('tb_interest_point-type', '01', '建筑物', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('common-rp_type', '02', '司法奖励', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('criminal_month_assess', '02', '每周电话每月书面汇报以及活动报告情况', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('tb_interest_point-type', '02', '公司', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('common-rp_type', '03', '行政处罚', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('criminal_month_assess', '03', '迁居审批请销假情况', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('tb_interest_point-type', '03', '住宅', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('common-rp_type', '04', '司法处罚', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('criminal_month_assess', '04', '参加学习教育以及公益劳动情况', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('tb_interest_point-type', '04', '学校', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('evaluate_doc_type', '04-1', '调查报告封面', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('criminal_month_assess', '05', '参与社会活动情况', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('tb_interest_point-type', '05', '医院', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('evaluate_doc_type', '05-1', '被告人社区矫正可行性评估表', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('criminal_month_assess', '06', '其它应当加分情形', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('tb_interest_point-type', '06', '会场', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('evaluate_doc_type', '06-1', '被告人户籍证明', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('tb_interest_point-type', '07', '货站', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('evaluate_doc_type', '07-1', '可行性评估报告', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('tb_interest_point-type', '08', '火车站', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('evaluate_doc_type', '08-1', '调查笔录', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('tb_interest_point-type', '09', '机场', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('evaluate_doc_type', '09-1', '被告人谈话笔录', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('area_status', '1', '巡检片状态', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('check_result', '1', '正常', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('common-account_type', '1', '城镇户口', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('common-affiance', '1', '未婚', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('common-charge_type', '1', '贪污贿赂罪', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('common-edu_bg', '1', '硕士及以上', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('common-monitor_level', '1', '安全', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('common-outside_type', '1', '管制', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('common-sex', '1', '男', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('common-share_flag', '1', '共享', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('common-status', '1', '矫正', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('common-user_type', '1', '平台管理员', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('common-use_flag', '1', '正常', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('consign_class_type', '1', '调查中', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('CONSIGN_DOC_TYPE', '1', '起诉书', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('CONSIGN_TYPE', '1', '法院委托', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('danger_level', '1', '一般', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('danger_state', '1', '未调度', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('danger_type', '1', '安全隐患类型设置', NULL, NULL, 0);
INSERT INTO `ts_codebook` VALUES ('docment_type', '1', '刑释解教人员回归社会衔接管理办法', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('DOCUMENT_TYPE', '1', '基本情况登记表', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('equip-type', '1', '国内', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('feedback-radius', '1', '500', NULL, '任务反馈允许偏离任务点的距离', 1);
INSERT INTO `ts_codebook` VALUES ('hbxs_type', '1', '电话', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('location-posour', '1', 'SID/NID区域定位', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('lock_position', '1', '1200', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('lock_position_time', '1', '600', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('message_type', '1', '越界告警', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('nj_administrative_area', '1', '玄武区', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('node-type', '1', 'station', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('product_is_new', '1', '是', 2, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('qjzt_type', '1', '未销假', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('risk-cent', '1', '1', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('risk-level', '1', '高危', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('send_status', '1', '列队中', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('STATISTICS_ITEM', '1', '机构统计', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('task-level', '1', '一般', 0, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('task-pretime', '1', '10', NULL, '任务开始前提醒时间', 1);
INSERT INTO `ts_codebook` VALUES ('tb_alarm-confirm_status', '1', '误报', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('tb_alarm-type', '1', '考勤提醒', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('tb_dept-rank', '1', '司法所', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('tb_location-type', '1', '人工定位', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('tb_notice-display_position', '1', '在主界面显示', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('tb_notice-status', '1', '未发布', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('tb_notice-type', '1', '系统公告', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('tb_railings-type', '1', '禁出围栏', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('tb_riskassess-management', '1', '宽管', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('tb_specialist-political_status', '1', '中共党员', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('tb_specialist-professional_title', '1', '教授', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('tb_user-duty', '1', '局长', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('tb_user-staff_status', '1', '正常', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('tb_user-staff_type', '1', '平台端', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('tb_volunteer-rank', '1', '一级心理咨询师', NULL, '01', 1);
INSERT INTO `ts_codebook` VALUES ('ts_func-binding', '1', '无绑定', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('ts_login_log-login_result', '1', '成功', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('user_vip_flag', '1', '是', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('criminal_month_assess', '10', '加分合计', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('danger_type', '10', '阀门井沉陷', NULL, NULL, 0);
INSERT INTO `ts_codebook` VALUES ('docment_type', '10', '重新犯罪人员登记表', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('DOCUMENT_TYPE', '10', '帮教协议书', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('event-effect', '10', '低级', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('nj_administrative_area', '10', '雨花台区', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('node-type', '10', 'app', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('notice_type', '10', 'ddd', NULL, NULL, 0);
INSERT INTO `ts_codebook` VALUES ('risk-type', '10', '漏洞风险', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('tb_interest_point-type', '10', '工厂', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('evaluate_doc_type', '10-2', '环境评价意见书', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('danger_type', '11', '消防栓撞断', NULL, NULL, 0);
INSERT INTO `ts_codebook` VALUES ('docment_type', '11', '帮教转化典型情况记录', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('DOCUMENT_TYPE', '11', '帮教责任书', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('nj_administrative_area', '11', '江宁区', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('node-type', '11', 'atom', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('notice_type', '11', 'a', NULL, NULL, 0);
INSERT INTO `ts_codebook` VALUES ('tb_interest_point-type', '11', '其他', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('evaluate_doc_type', '11-2', '矫正方案', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('danger_type', '12', '消防栓漏水', NULL, NULL, 0);
INSERT INTO `ts_codebook` VALUES ('DOCUMENT_TYPE', '12', '安置帮教小组安置帮教情况', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('nj_administrative_area', '12', '溧水县', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('node-type', '12', 'service', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('notice_type', '12', '23', NULL, NULL, 0);
INSERT INTO `ts_codebook` VALUES ('evaluate_doc_type', '12-2', '工作对象登记表', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('danger_type', '13', '消防栓缺件', NULL, NULL, 0);
INSERT INTO `ts_codebook` VALUES ('DOCUMENT_TYPE', '13', '刑释解教人员撤帮审批表', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('nj_administrative_area', '13', '高淳县', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('node-type', '13', 'os', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('evaluate_doc_type', '13-2', '户口登记表', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('danger_type', '14', '阀门井无盖', NULL, NULL, 0);
INSERT INTO `ts_codebook` VALUES ('node-type', '14', 'data', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('evaluate_doc_type', '14-2', '户籍证明', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('danger_type', '15', '阀门井破损', NULL, NULL, 0);
INSERT INTO `ts_codebook` VALUES ('node-type', '15', 'net', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('evaluate_doc_type', '15-2', '调查笔录', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('danger_type', '16', '阀门井冒水', NULL, NULL, 0);
INSERT INTO `ts_codebook` VALUES ('danger_type', '17', '阀门井被埋', NULL, NULL, 0);
INSERT INTO `ts_codebook` VALUES ('danger_type', '18', '阀门井沉陷', NULL, NULL, 0);
INSERT INTO `ts_codebook` VALUES ('location-posour', '18', '手机AGPS（包括AGPS+AFLT的混合模式）', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('danger_type', '19', '水表箱无盖', NULL, NULL, 0);
INSERT INTO `ts_codebook` VALUES ('check_result', '2', '扣分', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('common-account_type', '2', '农村户口', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('common-affiance', '2', '已婚', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('common-charge_type', '2', '妨碍社会管理秩序罪', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('common-edu_bg', '2', '本科', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('common-monitor_level', '2', '一般', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('common-outside_type', '2', '缓刑', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('common-sex', '2', '女', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('common-status', '2', '解矫', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('common-user_type', '2', '地市管理员', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('consign_class_type', '2', '适合社区矫正', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('CONSIGN_DOC_TYPE', '2', '环境评价意见书', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('CONSIGN_TYPE', '2', '监狱委托', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('criminal_status_chg-type', '2', '到期解矫', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('danger_level', '2', '紧急', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('danger_state', '2', '执行中', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('danger_type', '2', '安全隐患类型设置2', NULL, NULL, 0);
INSERT INTO `ts_codebook` VALUES ('docment_type', '2', '刑释解教人员规范化管理通知', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('DOCUMENT_TYPE', '2', '就业安置情况登记表', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('equip-type', '2', '海外', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('feedback-radius', '2', '巡检', NULL, NULL, 0);
INSERT INTO `ts_codebook` VALUES ('hbxs_type', '2', '书面', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('message_type', '2', '信息交互', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('nj_administrative_area', '2', '白下区', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('node-type', '2', 'Nsc', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('notice_type', '2', '好好', NULL, NULL, 0);
INSERT INTO `ts_codebook` VALUES ('product_is_new', '2', '全部', 1, NULL, 0);
INSERT INTO `ts_codebook` VALUES ('qjzt_type', '2', '已销假', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('risk-cent', '2', '2', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('risk-level', '2', '中危', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('send_status', '2', '发送中', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('STATISTICS_ITEM', '2', '学历统计', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('task-level', '2', '5', NULL, NULL, 0);
INSERT INTO `ts_codebook` VALUES ('tb_alarm-confirm_status', '2', '越界', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('tb_alarm-type', '2', '考勤提醒', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('tb_dept-rank', '2', '区司法局', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('tb_location-type', '2', '定时定位', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('tb_notice-display_position', '2', '在登陆页面显示', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('tb_notice-status', '2', '已发布', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('tb_notice-type', '2', '司法局公告', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('tb_railings-type', '2', '禁入围栏', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('tb_riskassess-management', '2', '普管', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('tb_specialist-political_status', '2', '预备党员', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('tb_specialist-professional_title', '2', '副教授', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('tb_user-duty', '2', '科长', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('tb_user-staff_status', '2', '离职', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('tb_volunteer-rank', '2', '二级心理咨询师', NULL, '02', 1);
INSERT INTO `ts_codebook` VALUES ('ts_func-binding', '2', '有绑定', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('ts_login_log-login_result', '2', '用户名不存在', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('criminal_month_assess', '20', '考核扣分情况', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('danger_type', '20', '水表箱破损', NULL, NULL, 0);
INSERT INTO `ts_codebook` VALUES ('event-effect', '20', '中级', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('location-posour', '20', '手机AFLT', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('risk-type', '20', '基线风险', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('danger_type', '21', '水表箱内漏水', NULL, NULL, 0);
INSERT INTO `ts_codebook` VALUES ('danger_type', '22', '路漏（路面积水）', NULL, NULL, 0);
INSERT INTO `ts_codebook` VALUES ('location-posour', '22', 'A-GPS + AFLT', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('danger_type', '23', '路漏（路面冒水）', NULL, NULL, 0);
INSERT INTO `ts_codebook` VALUES ('danger_type', '24', '路漏（路面淹水）', NULL, NULL, 0);
INSERT INTO `ts_codebook` VALUES ('danger_type', '25', '施工损坏（≤DN50）', NULL, NULL, 0);
INSERT INTO `ts_codebook` VALUES ('danger_type', '26', '施工损坏（＞DN50）', NULL, NULL, 0);
INSERT INTO `ts_codebook` VALUES ('danger_type', '27', '进水管漏水', NULL, NULL, 0);
INSERT INTO `ts_codebook` VALUES ('danger_type', '28', '拆表户漏水', NULL, NULL, 0);
INSERT INTO `ts_codebook` VALUES ('danger_type', '29', '泄气漏水', NULL, NULL, 0);
INSERT INTO `ts_codebook` VALUES ('check_result', '3', '未确认', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('common-affiance', '3', '离异', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('common-charge_type', '3', '危害国家安全罪', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('common-edu_bg', '3', '大专', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('common-monitor_level', '3', '重视', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('common-outside_type', '3', '假释', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('common-status', '3', '重新犯罪', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('common-user_type', '3', '法人用户', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('consign_class_type', '3', '不适合社区矫正', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('CONSIGN_DOC_TYPE', '3', '矫正方案', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('CONSIGN_TYPE', '3', '检察院委托', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('criminal_status_chg-type  ', '3', '重新犯罪', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('danger_state', '3', '完成', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('danger_type', '3', '消防栓撞断', NULL, NULL, 0);
INSERT INTO `ts_codebook` VALUES ('docment_type', '3', '刑释解教人员安置帮教工作规范管理实施意见', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('DOCUMENT_TYPE', '3', '走访情况工作记录', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('feedback-radius', '3', '巡检', NULL, NULL, 0);
INSERT INTO `ts_codebook` VALUES ('hbxs_type', '3', '当面', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('message_type', '3', '查询积分', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('nj_administrative_area', '3', '秦淮区', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('node-type', '3', 'command', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('notice_type', '3', '公司通告', NULL, NULL, 0);
INSERT INTO `ts_codebook` VALUES ('risk-cent', '3', '3', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('risk-level', '3', '低危', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('send_status', '3', '发送成功', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('STATISTICS_ITEM', '3', '年龄统计', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('task-level', '3', '3', NULL, NULL, 0);
INSERT INTO `ts_codebook` VALUES ('tb_alarm-type', '3', '任务超时', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('tb_dept-rank', '3', '市司法局', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('tb_location-type', '3', '快速定位', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('tb_notice-display_position', '3', '都显示', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('tb_notice-type', '3', '司法所公告', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('tb_riskassess-management', '3', '严管', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('tb_specialist-political_status', '3', '共青团员', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('tb_specialist-professional_title', '3', '讲师', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('tb_user-duty', '3', '所长', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('tb_volunteer-rank', '3', '三级心理咨询师', NULL, '03', 1);
INSERT INTO `ts_codebook` VALUES ('ts_func-binding', '3', '被绑定', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('ts_login_log-login_result', '3', '密码错误', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('criminal_month_assess', '30', '扣分合计', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('danger_type', '30', '工地内漏水', NULL, NULL, 0);
INSERT INTO `ts_codebook` VALUES ('event-effect', '30', '严重', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('risk-type', '30', '攻击预警风险', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('danger_type', '31', '压占管线', NULL, NULL, 0);
INSERT INTO `ts_codebook` VALUES ('danger_type', '32', '施工威胁', NULL, NULL, 0);
INSERT INTO `ts_codebook` VALUES ('danger_type', '33', '道路沉陷', NULL, NULL, 0);
INSERT INTO `ts_codebook` VALUES ('danger_type', '34', '设施围禁', NULL, NULL, 0);
INSERT INTO `ts_codebook` VALUES ('danger_type', '35', '私用消防', NULL, NULL, 0);
INSERT INTO `ts_codebook` VALUES ('danger_type', '36', '私改私移', NULL, NULL, 0);
INSERT INTO `ts_codebook` VALUES ('danger_type', '37', '破坏供水设施', NULL, NULL, 0);
INSERT INTO `ts_codebook` VALUES ('danger_type', '38', '路漏', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('danger_type', '39', '施工损坏', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('common-affiance', '4', '丧偶', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('common-charge_type', '4', '危害公共安全罪', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('common-edu_bg', '4', '中专', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('common-monitor_level', '4', '严重', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('common-outside_type', '4', '监外执行', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('common-status', '4', '逃脱', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('common-user_type', '4', '普通用户', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('CONSIGN_TYPE', '4', '少管所委托', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('criminal_status_chg-type  ', '4', '脱逃', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('danger_type', '4', '消防栓漏水', NULL, NULL, 0);
INSERT INTO `ts_codebook` VALUES ('docment_type', '4', '安置帮教工作领导小组名单', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('DOCUMENT_TYPE', '4', '帮教小组成员', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('hbxs_type', '4', '口头', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('message_type', '4', '随机抽查', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('nj_administrative_area', '4', '建邺区', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('notice_type', '4', '江苏鸿信通告', NULL, NULL, 0);
INSERT INTO `ts_codebook` VALUES ('risk-cent', '4', '4', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('send_status', '4', '发送失败', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('tb_alarm-type', '4', 'GPS定位异常', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('tb_dept-rank', '4', '其他', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('tb_location-type', '4', '短信指令定位', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('tb_riskassess-management', '4', '剥夺政治权利', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('tb_specialist-political_status', '4', '群众', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('tb_specialist-professional_title', '4', '研究员', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('tb_user-duty', '4', '工作人员', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('ts_login_log-login_result', '4', '验证码错误 ', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('criminal_month_assess', '40', '本月得分', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('danger_type', '40', '其他漏水', NULL, NULL, 0);
INSERT INTO `ts_codebook` VALUES ('event-effect', '40', '致命', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('risk-type', '40', '病毒风险', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('criminal_month_assess', '41', '奖惩计分', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('danger_type', '41', '消防栓', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('criminal_month_assess', '42', '调节计分', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('danger_type', '42', '阀门井', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('danger_type', '43', '水表箱', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('danger_type', '44', '安全隐患', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('danger_type', '45', '违法违规', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('danger_type', '46', 'test', NULL, NULL, 0);
INSERT INTO `ts_codebook` VALUES ('danger_type', '47', 'aa', NULL, NULL, 0);
INSERT INTO `ts_codebook` VALUES ('danger_type', '48', 'bb', NULL, NULL, 0);
INSERT INTO `ts_codebook` VALUES ('danger_type', '49', 'cc', NULL, NULL, 0);
INSERT INTO `ts_codebook` VALUES ('common-charge_type', '5', '破坏社会主义市场经济秩序罪', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('common-edu_bg', '5', '高中', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('common-monitor_level', '5', '特别严重', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('common-outside_type', '5', '剥夺政治权利', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('common-status', '5', '下落不明', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('CONSIGN_TYPE', '5', '劳教所委托', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('criminal_status_chg-type  ', '5', '下落不明', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('danger_type', '5', '消防栓缺件', NULL, NULL, 0);
INSERT INTO `ts_codebook` VALUES ('docment_type', '5', '安置帮教工作站工作人员名单', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('DOCUMENT_TYPE', '5', '委托管理情况登记', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('hbxs_type', '5', '其它', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('message_type', '5', '集中学习', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('nj_administrative_area', '5', '鼓楼区', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('notice_type', '5', '天天向前', NULL, NULL, 0);
INSERT INTO `ts_codebook` VALUES ('risk-cent', '5', '5', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('tb_specialist-political_status', '5', '民主党派人士', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('tb_specialist-professional_title', '5', '副研究员', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('tb_user-duty', '5', '管理员', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('criminal_month_assess', '50', '累计得分', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('danger_type', '50', '11', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('common-charge_type', '6', '侵犯公民人身权利、民主权利罪', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('common-edu_bg', '6', '初中', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('common-status', '6', '脱管漏管', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('criminal_status_chg-type ', '6', '脱管漏管', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('danger_type', '6', '阀门井无盖', NULL, NULL, 0);
INSERT INTO `ts_codebook` VALUES ('docment_type', '6', '安置帮教工作领导小组会议记录', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('DOCUMENT_TYPE', '6', '重新违法犯罪情况登记', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('location-posour', '6', '网络小区号', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('message_type', '6', '公益劳动', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('nj_administrative_area', '6', '下关区', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('notice_type', '6', '天都峰', NULL, NULL, 0);
INSERT INTO `ts_codebook` VALUES ('tb_specialist-political_status', '6', '无党派人士', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('tb_user-duty', '6', '其他', NULL, '', 1);
INSERT INTO `ts_codebook` VALUES ('criminal_month_assess', '61', '矫正执法人员意见', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('criminal_month_assess', '62', '司法所长', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('common-charge_type', '7', '侵犯财产罪', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('common-edu_bg', '7', '小学', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('common-status', '7', '超期解矫', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('criminal_status_chg-type  ', '7', '超期解矫', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('danger_type', '7', '阀门井破损', NULL, NULL, 0);
INSERT INTO `ts_codebook` VALUES ('docment_type', '7', '安置帮教工作情况分析记录', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('DOCUMENT_TYPE', '7', '帮教情况记录', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('nj_administrative_area', '7', '浦口区', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('notice_type', '7', '公司公告', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('common-charge_type', '8', '渎职罪', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('common-edu_bg', '8', '文盲', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('common-status', '8', '死亡', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('criminal_status_chg-type  ', '8', '死亡', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('danger_type', '8', '阀门井冒水', NULL, NULL, 0);
INSERT INTO `ts_codebook` VALUES ('docment_type', '8', '刑释解教人员重点帮控登记表', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('DOCUMENT_TYPE', '8', '继续帮教情况记录', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('location-posour', '8', '混合cell/ sector', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('nj_administrative_area', '8', '六合区', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('notice_type', '8', '技术资料', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('common-charge_type', '9', '其他', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('common-status', '9', '收监执行', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('danger_type', '9', '阀门井被埋', NULL, NULL, 0);
INSERT INTO `ts_codebook` VALUES ('docment_type', '9', '剥夺政治权利人员登记表', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('DOCUMENT_TYPE', '9', '出监(所)通知书及其他', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('nj_administrative_area', '9', '栖霞区', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('notice_type', '9', '管理规定', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('common-status', '99', '其他', NULL, NULL, 1);
INSERT INTO `ts_codebook` VALUES ('criminal_status_chg-type  ', '99', '其它', NULL, NULL, 1);